movieData = [
	{
		"id": 1,
		"titleId": 2,
		"name": "Bud Abbott and Lou Costello in Hollywood",
		"type": "FF",
		"description": "A pair of wacky lackeys try to take Tinseltown by storm.",
		"synopsis": "At the busy Hollywood Shop, the \"barber shop to the stars,\" seasoned barber Buzz Kurtis tries to teach his clumsy pal Abercrombie how to shave customers. Abercrombie practices on an air-filled balloon covered with shaving cream, which explodes in his face when he loses control of the razor. Later, at the office of motion picture agent Norman Royce, Buzz and Abercrombie are in the middle of giving the agent a shave and a shoeshine when Jeff Parker, a singer from Des Moines, arrives looking for an agent to represent him. Impressed by Jeff's singing, Norman decides to recommend him for the romantic lead opposite Claire Warren in director Dennis Kavanaugh's next picture. Leading man Gregory LeMaise was to star in the film, but gave up the part and canceled his contract with Norman. The seeming ease with which Norman makes lucrative movie deals persuades Buzz and Abercrombie to become agents themselves, and they begin by convincing Jeff that he should be their first client. A short time later, at the main entrance to Mammoth Studios, Buzz and Abercrombie accidentally crash their car into Kavanaugh's car and are ordered off the lot. While Kavanaugh signs Jeff to star in his new film, Buzz and Abercrombie try to elude the studio police long enough to find Kavanaugh. Later, to celebrate Jeff's new contract, Kavanaugh, Buzz and Abercrombie take the new star to Ciro's nightclub. There Gregory tells Kavanaugh that he has changed his mind and has decided to resume his role in the film. Kavanaugh, not wanting to take a risk on Jeff, takes Gregory back and cancels his contract with Jeff. Claire, who has fallen in love with Jeff, vows to fight Kavanaugh's decision, but Jeff tells her that he has decided to give up his attempt to break into show business and that he will be returning to Des Moines. Desperate to keep their client from leaving Hollywood, Buzz and Abercrombie decide to prevent Gregory from appearing in the film by devising a plan to get the actor arrested. As part of their plan, Buzz and Abercrombie board the actor's boat and provoke him into committing an assault against Abercrombie. Gregory punches Abercrombie so hard, though, that he is propelled into the water. Although Abercrombie swims back to shore, Buzz tells him to hide so that he can accuse Gregory of murder. When Buzz threatens to go to the police, Gregory drops out of sight and is labeled a fugitive by the press. Later, at a bar, Gregory discovers that Abercrombie is alive and chases after him. The chase continues through the amusement park set of Kavanaugh's film, and their ensuing wild roller coaster ride is captured on film. Although the chase adds just the right amount of excitement to the film to make it a hit, Abercrombie and Buzz soon find themselves back at their old jobs at the barber shop.",
		"mpaaRating": "NULL",
		"releaseYear": 1945,
		"country": "United States",
		"duration": 4980,
		"sound": "Mono",
		"color": "Black and White",
		"filmLength": "7423",
		"drupalID": 0,
		"afiID": 734,
		"BaselineID": "",
		"TribuneID": "",
		"runtimeMinutes": "83",
		"profileImageUrl": "http://i.cdn.turner.com/v5cache/TCM/Images/Dynamic/i318/abbottandcostelloinhollywood1945_2_450x254_02142014014409.jpg"
	}, {
		"id": 2,
		"titleId": 6,
		"name": "Torchy Blane, the Adventurous Blonde",
		"type": "FF",
		"description": "Reporter Torchy Blane walks out on her own wedding to solve the case of a murdered actor.",
		"synopsis": "Newspaper reporter Torchy Blane is handed a telegram, which she reads before realizing it actually was sent to Theresa Gray, the woman sitting next to her on the train.  Torchy's telegram, when she gets it, is from policeman Steve McBride, announcing that he will have a minister waiting to marry them when her train arrives.  Worried that her marriage to Steve will put Torchy ahead in covering the police beat, several reporters decide to play a practical joke on her and postpone her wedding at the same time.  The reporters hire an actor to play dead and phone Steve with the news. They hope that Torchy will report the death and that a second paper owned by publisher Mortimer Gray will embarrass her by printing the truth.  Then, Harvey Hammond, the actor, is actually murdered, and Torchy beats the other reporters to the story as usual. The suspects in his death are Grace Brown, an actress in Hammond's company; her boyfriend Hugo Brand; Mrs. Jenny Hammond, who was jealous of Hammond's love for Grace; and Theresa Gray, Hammond's discarded lover. Torchy frames Theresa for the murder in order to force a confession from publisher Gray, her husband. Gray, who knew about the proposed joke, was jealous of his wife's relationship with Hammond and seized the opportunity to kill him.  He now confesses before taking poison.  Cleared of any suspicion, Hugo and Grace are married by Torchy's waiting magistrate, and Torchy and Steve postpone their wedding once again.",
		"mpaaRating": "NULL",
		"releaseYear": 1937,
		"country": "United States",
		"duration": 3600,
		"sound": "Mono",
		"color": "Black and White",
		"filmLength": "not available",
		"drupalID": 0,
		"afiID": 4848,
		"BaselineID": "",
		"TribuneID": "",
		"runtimeMinutes": "60-61 or 65",
		"profileImageUrl": "http://i.cdn.turner.com/v5cache/TCM/Images/Dynamic/i218/torchyblanetheadventurousblonde1937_450x254_07232013115309.jpg"
	}, {
		"id": 3,
		"titleId": 10,
		"name": "Anchors Aweigh",
		"type": "FF",
		"description": "A pair of sailors on leave try to help a movie extra become a singing star.",
		"synopsis": "After eight months at sea, sailors Clarence Doolittle and Joseph Brady are granted a four-day shore leave in Hollywood, California. Joe, an incorrigible philanderer, plans to see one of his sweethearts while on leave, and later offers the shy and bookish Clarence advice on how to meet women. Clarence and Joe set out to find their shore leave romances but their plans are soon thwarted by a police sergeant, who demands that they help him with an unusual situation involving a young boy named Donald Martin. The police sergeant explains that Donald has run away from home to join the Navy and refuses to tell the police where he lives. Joe and Clarence easily win Donald's trust and agree to escort him home, where he lives with his widowed aunt, Susan Abbott. While Joe is eager to avoid any further involvement with the young boy, Clarence falls in love with Susan and promises to return the following day. When Joe and Clarence return to Susan's, they meet Bertram Kraler, a man Susan hopes will introduce her to the famous maestro José Iturbi. As Susan dresses for her date, Joe, convinced that Bertram is a new suitor who will only get in the way of Clarence's romantic pursuit of Susan, scares Bertram away by suggesting that Susan is a notorious Navy sweetheart. When Susan learns what Joe has done, she breaks down in tears and believes that her chances at breaking into show business are doomed. Joe tries to comfort Susan but only makes matters worse for himself when he tells her that Clarence and Iturbi are good friends and that he can arrange an audition for her. With her faith in Joe and Clarence restored, Susan takes them to a Mexican restaurant and sings a song for them. While Joe dances with Susan, Clarence meets a friendly waitress, whom he nicknames \"Brooklyn,\" after their hometown. Realizing that he must honor Joe's promise to Susan for an audition with Iturbi, Clarence tries unsuccessfully to meet with Iturbi at the Metro-Goldwyn-Mayer studios. Meanwhile, Joe, who has become quite fond of Donald and Susan, tells Donald's classmates a story about his experience in a mythical kingdom populated by animals: In the kingdom, Joe discovers that the animals that live there are sad because their mouse king has prohibited them from singing. Determined to help the animals, Joe visits their unhappy king and shows him the beauty of song and dance. Joe's story concludes with the king repealing his edict and allowing the animals to sing. As a new romance develops between Clarence and Brooklyn, Joe falls in love with Susan. One day, Susan has a chance encounter with Iturbi and discovers that Joe and Clarence have been deceiving her and do not really know Iturbi. Feeling embarrassed and betrayed, Susan breaks down in tears. Iturbi, however, understands her situation and arranges a screen test for her. The test is a great success, and Iturbi soon presents Susan at one of his shows. Before returning to his ship, Joe makes amends with Susan, and Clarence and Brooklyn embrace.",
		"mpaaRating": "NULL",
		"releaseYear": 1945,
		"country": "United States",
		"duration": 8340,
		"sound": "Mono (Western Electric Sound System)",
		"color": "Color (Technicolor)",
		"filmLength": "12542",
		"drupalID": 0,
		"afiID": 24312,
		"BaselineID": "",
		"TribuneID": "",
		"runtimeMinutes": "138-140",
		"profileImageUrl": "http://i.cdn.turner.com/v5cache/TCM/Images/Dynamic/i434/anchorsaweigh1945_10_450x254_03282017095442.jpg"
	}, {
		"id": 4,
		"titleId": 11,
		"name": "Andy Hardy Gets Spring Fever",
		"type": "FF",
		"description": "A teenage boy falls in love with his drama teacher.",
		"synopsis": "As winter disappears in Carvel, usually serious-minded Judge James K. Hardy finds himself gazing out his courtroom window and thinking of spring.  After court is recessed, the judge is visited by chemist Mark Hansen and promoter James Willis, who inform him that some gravelly land previously thought worthless and set aside for an acqueduct that was never built, is actually rich in bauxite, a mineral needed to make aluminum. Though the men want to start to work reclaiming the bauxite right away, the judge decides to get a sample of the soil himself and have it independently analyzed.  That same day, the judge's teenage son Andy is snubbed by his girl friend, Polly Benedict, who has a crush on Ensign Charles Copley, who is working in Carvel. Andy's hurt feelings are soon alleviated by Rose Meredith, a new, young drama teacher at Carvel High, on whom Andy develops a tremendous crush.  Soon the judge's chemical report comes back revealing that the soil sample is what Hansen and Willis claimed it was.  He then excitedly decides to invest his own money and urge friends to capitalize on the venture as well. Soon Marian Hardy, the judge's daughter, who wants to become a career woman, gets a job as Hansen and Willis' secretary.  As the weeks pass, while the judge and his friends anticipate great profits from the bauxite and Marian works at the office, Andy works hard to impress Miss Meredith in rehearsals for the school play.  One day, Marian comes home from the office and informs her father that Willis and Hansen have secretly left town with all of the money earmarked for the project. Knowing that he has been duped and feeling guilty that he urged friends to join him in the venture, the judge decides to call a meeting of the share holders to confess everything.  Just before the meeting, however, he learns that the city is anxious to buy the gravel on the land for a new highway. Although he still blames himself for the near financial disaster, his friends hold themselves equally responsible and are happy to learn that the gravel sale will enable them to break even on their investments.  Later that day, Andy announces that he plans to quit school and marry Miss Meredith, to whom he has just proposed.  Though his father gently tries to warn him about the problems he will encounter, Andy is convinced that his situation will work out.  Miss Meredith, who was touched by Andy's proposal, tells him that she will give him an answer after the school play.  During the intermission, however, when Andy sees her kiss her fiancé, who has just come to visit her, he realizes that she will not marry him. Though hurt, Andy continues in the play.  Finally, after the play is greeted with applause by the audience, Polly goes to Andy to make up and the entire Hardy family happily return home.",
		"mpaaRating": "NULL",
		"releaseYear": 1939,
		"country": "United States",
		"duration": 5100,
		"sound": "Mono (Western Electric Sound System)",
		"color": "Black and White",
		"filmLength": "not available",
		"drupalID": 0,
		"afiID": 8415,
		"BaselineID": "",
		"TribuneID": "",
		"runtimeMinutes": "85 or 87",
		"profileImageUrl": "http://i.cdn.turner.com/v5cache/TCM/Images/Dynamic/i231/andyhardygetsspringfever1939_450x255_09202013114829.jpg"
	}, {
		"id": 5,
		"titleId": 12,
		"name": "Andy Hardy Meets Debutante",
		"type": "FF",
		"description": "A teenage boy goes into debt to court a Manhattan socialite.",
		"synopsis": "Moonstruck by the image of Daphne Fowler, New York's reigning debutante, Carvel's Andy Hardy brags to his friends \"Beezy\" and Polly Benedict, the editors of his high school paper, that he is good friends with the socialite, whom he has never met.  Andy's words return to haunt him when his father, Judge James K. Hardy, packs his family off to New York to protect the endowment of the Carvel orphanage.  When Beezy and Polly threaten to print the story of Andy's romance, Andy realizes that to save face, he must prove his friendship with Daphne, and sets out to meet her.  In New York, Andy is greeted by his old friend, Betsy Booth, who has a crush on Andy, but he ignores Betsy in his pursuit of Daphne.  Andy soon discovers that royalty does not mingle with the common folk, and so he dons airs of affluence to meet Daphne.  When Andy hears Daphne's radio broadcast inviting her listeners to a dog lovers benefit at an expensive restaurant, Andy eagerly attends, but his pretext of wealth gets him in trouble when he is unable to pay his huge bill and is humiliated by the club's manager.  Judge Hardy is also having difficulties in New York, and it looks as if he might lose his case for the orphanage.  Andy's misery mounts when he receives an advance copy of the school paper featuring the humiliating story of his romance with Daphne. Recognizing his son's unhappiness, Judge Hardy tries to make Andy realize that all men are created equal and snobbery is not to be admired, but he fails in his mission. Although the principles of equal opportunity fail to touch Andy, they inspire Judge Hardy to recast his case for the orphanage, and he wins the suit in court. The judge's victory proves to Andy the importance of equality and he renounces his snobbery.  Andy then confides his predicament to Betsy, who solves his problems by introducing him to her good friend Daphne, thus allowing Andy to return home triumphant with a photo of Daphne embracing him.",
		"mpaaRating": "NULL",
		"releaseYear": 1940,
		"country": "United States",
		"duration": 5280,
		"sound": "Mono (Western Electric Sound System)",
		"color": "Black and White",
		"filmLength": "not available",
		"drupalID": 0,
		"afiID": 8162,
		"BaselineID": "",
		"TribuneID": "",
		"runtimeMinutes": "85, 87 or 89",
		"profileImageUrl": "http://i.cdn.turner.com/v5cache/TCM/Images/Dynamic/i231/andyhardymeetsdebutante1940_450x255_09202013114853.jpg"
	}, {
		"id": 964,
		"titleId": 610,
		"name": "Casablanca",
		"type": "FF",
		"description": "An American saloon owner in North Africa is drawn into World War II when his lost love turns up.",
		"synopsis": "During World War II, Casablanca, Morocco is a waiting point for throngs of desperate refugees fleeing Nazi-occupied Europe.  Exit visas, which are necessary to leave the country, are at a premium, so when two German couriers carrying letters of transit signed by General DeGaulle are murdered and the letters stolen, German Major Strasser and Louis Renault, the prefecture of police, are eager to find the documents. Strasser is particularly concerned that the letters not be sold to Victor Lazlo, the well-known Czech resistance leader, who is rumored to be on his way to Casablanca.  That night, Renault and Strasser search for the killer at Rick's Café Americain, a popular nightclub run by the mysterious American ex-patriot Richard Blaine.  Earlier, Ugarte, a shady dealer in exit visas, had asked Rick to hold the stolen letters temporarily, explaining that he has a buyer for them and with the money from their sale, he plans to leave Casablanca.   Although Rick fought on the side of the loyalists in Spain, he has grown cynical, and when Renault advises him not to interfere with Ugarte's arrest, Rick replies \"I stick my neck out for nobody.\"  He makes a bet with Renault, however, that Lazlo will manage to leave Casablanca despite German efforts to stop him.  After Ugarte is arrested, Lazlo and his companion, Ilsa Lund, arrive at Rick's.  Ilsa recognizes Sam, the piano player, and while Lazlo makes covert contact with the underground, Ilsa insists that Sam play the song \"As Time Goes By.\" Reluctantly, Sam agrees, and a furious Rick, who had ordered him never to play the song again, emerges from his office to stop him.  Rick is taken aback when he sees Ilsa, whom he knew in Paris.  Later, after the café is closed, Rick remembers his love affair with Ilsa:  After a brief happy time together, the Nazis invade Paris and, worried that Rick will be in danger because of his record, Ilsa advises him to leave the city.  He refuses to go without her, and she agrees to meet him at the train station. Instead of coming, though, she sends him a farewell note, and Sam and Rick leave just ahead of the Nazis.  Rick's thoughts return to the present with Ilsa's arrival at the café.  She tries to explain her actions, but when a drunken Rick accuses her of being a tramp, she walks out.  The following day, Lazlo and Ilsa meet with Renault and, there they learn that Ugarte has been killed while in police custody.  After Rick helps a young Romanian couple win enough money at roulette to allow them to leave the country, Lazlo, suspecting that Rick has the letters, asks to buy them.  Rick refuses and, when Lazlo asks his reasons, suggests that he ask Ilsa. Angered when Rick allows his orchestra to accompany a rousing rendition of \"La Marseillaise,\" Strasser orders the closing of the Café.  That night, while Lazlo attends an underground meeting, Ilsa meets Rick and explains that she stayed behind in Paris because, on the day Rick left Paris she had learned that Lazlo, her husband, whom she had married in secret and thought dead, was alive.  Now realizing that they still love each other, Ilsa tells Rick that he must made decisions for both of them. Meanwhile, the police break up the underground meeting, and Lazlo takes refuge at Rick's.  Before he is arrested, he begs Rick to use the letters to take Ilsa away from Casablanca.  The next day, Rick sells the café to his competitor Ferare, the owner of the Blue Parrot, and tricks Renault into releasing Lazlo from prison.  They head for the airport, but Renault has managed to alert Strasser, who hurries after them.  At the airport, Rick tells Ilsa, who thought that she would be staying with him, that she is to leave with Lazlo because she gives meaning to his work.  He then tells Lazlo that he and Ilsa loved each other in Paris, and that she pretended she was still in love with him in order to get the letters.  Lazlo, who understands what really happened, welcomes Rick back to the fight before he and Ilsa board the plane. Strasser arrives just as the airplane is about to take off and when he tries to delay the flight, Rick shoots him.  Renault then quickly telephones the police, but instead of turning in Rick, he advises them to \"round up the usual suspects,\" and the two men leave Casablanca for the Free French garrison at Brassaville.  It is, Rick says, \"the beginning of a beautiful friendship.\"",
		"mpaaRating": "PG",
		"releaseYear": 1942,
		"country": "United States",
		"duration": 6120,
		"sound": "Mono (RCA Sound System)",
		"color": "Black and  White",
		"filmLength": "9221",
		"drupalID": 0,
		"afiID": 27175,
		"BaselineID": "",
		"TribuneID": "",
		"runtimeMinutes": "99",
		"profileImageUrl": "http://i.cdn.turner.com/v5cache/TCM/Images/Dynamic/i385/Casablanca1942_610_450x254_01252016035436.jpg"
	}, {
		"id": 15716,
		"titleId": 22123,
		"name": "Star Wars: A New Hope",
		"type": "FF",
		"description": "In a distant galaxy, a long time ago, young Luke Skywalker assembles his motley crew of allies including space rogue Han Solo and two \"droids\" -- C3PO and R2D2 -- to rescue Princess Leia, the rebel leader of her planet from the clutches of the evil Empire as embodied by its enforcer Darth Vader.",
		"synopsis": "In a distant galaxy, a long time ago, young Luke Skywalker assembles his motley crew of allies including space rogue Han Solo and two \"droids\" -- C3PO and R2D2 -- to rescue Princess Leia, the rebel leader of her planet from the clutches of the evil Empire as embodied by its enforcer Darth Vader.",
		"mpaaRating": "PG",
		"releaseYear": 1977,
		"country": "United States (USA)",
		"duration": 7260,
		"sound": "70 mm 6-Track (70 mm prints), DTS 70 mm (special edition) (70 mm prints) (Europe), DTS (special edition), Dolby Digital (special edition), Dolby (35 mm prints), SDDS (special edition)",
		"color": "Color (Technicolor)",
		"filmLength": "NULL",
		"drupalID": 0,
		"afiID": 0,
		"BaselineID": "",
		"TribuneID": "",
		"runtimeMinutes": "121",
		"profileImageUrl": "http://filmfestival.tcm.com/wp-content/uploads/2019/02/StarWars_470x350.jpg"
	}
];
